version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "weekly"
    allow:
      - dependency-type: "development"
    ignore:
      - dependency-name: "@radix-ui/*"
      - dependency-name: "clsx"
      - dependency-name: "lucide-react"
      - dependency-name: "tailwindcss"
      - dependency-name: "tailwind-merge"
      - dependency-name: "sonner"
      - dependency-name: "recharts"
      - dependency-name: "vaul"
